port: 15000
conda-exec: "conda"

processes:
  obj-detection:
    conda_env: "rbc_objdetect"
    exec_cmd: "python3 robocup2022-cv-object-detection/object_detection.py"
  what-is-that:
    conda_env: "rbc_whatisthat"
    exec_cmd: "python3 robocup2022-cv-what-is-that/what_is_that_v2.py"
  person-track:
    conda_env: "rbc_persontrack"
    exec_cmd: "python3 robocup2022-cv-person-tracker/person_tracker.py"

states:
  default:
    - obj-detection
    - what-is-that
    - person-track
  problem1:
    - obj-detection
    - what-is-that
  problem2:
    - person-track