port: 15000
conda-exec: "conda"

processes:
  person-track:
    conda_env: "new-person-tracker"
    exec_cmd: "python3 /home/eic/cv/robocup2022-cv-person-tracker/person_tracker.py"
  obj-detect-yolov4:
    conda_env: "yolov4"
    exec_cmd: "python3 /home/eic/cv/robocup2022-cv-YOLOv4/object_detection.py"
  obj-detect-yolov5:
    conda_env: "yolov5"
    exec_cmd: "python3 /home/eic/cv/robocup2022-cv-yolov5/yolov5.py"
  face-recog:
    conda_env: "face-reg"
    exec_cmd: "python3 /home/eic/cv/face-recognition/facerecog.py"
  wit-yolov5:
    conda_env: "what-is-that-yolov5"
    exec_cmd: "python3 /home/eic/cv/robocup2022-cv-what-is-that-yolov5/what_is_that_yolov5.py"
  wit-yolor:
    conda_env: "what-is-that-yolor"
    exec_cmd: "python3 /home/eic/cv/robocup2022-cv-what-is-that/what_is_that.py"

states:
  default:
    - person-track
    - obj-detect-yolov4
    - obj-detect-yolov5
    - face-recog
    - wit-yolov5
    - wit-yolor
  test_problem1:
    - person-track
    - obj-detect-yolov4
    - obj-detect-yolov5