port: 15000
conda-exec: "conda"

processes:
  process1:
    conda_env: "env_python38"
    exec_dir: "~/Desktop/cv-main/"
    exec_cmd: "python3 test.py"
  process2:
    conda_env: "env_python38"
    exec_dir: "~/Desktop/cv-main/"
    exec_cmd: "python3 test.py"
  process3:
    conda_env: "env_python38"
    exec_dir: "~/Desktop/cv-main/"
    exec_cmd: "python3 test.py"

states:
  default:
    - process1
    - process2
    - process3