port: 15000
conda-exec: "conda"

processes:
  person-track:
    conda_env: "new-person-tracker"
    exec_dir: "/home/eic/cv/robocup2022-cv-person-tracker/"
    exec_cmd: "python3 person_tracker.py"
  obj-yolov4:
    conda_env: "yolov4"
    exec_dir: "/home/eic/cv/robocup2022-cv-YOLOv4/"
    exec_cmd: "python3 object_detection.py"
  obj-yolov5:
    conda_env: "yolov5"
    exec_dir: "/home/eic/cv/robocup2022-cv-yolov5/"
    exec_cmd: "python3 yolov5.py"
  face-recog:
    conda_env: "face-reg"
    exec_dir: "/home/eic/cv/face-recognition/"
    exec_cmd: "python3 facerecog.py"
  wit-yolov5:
    conda_env: "what-is-that-yolov5"
    exec_dir: "/home/eic/cv/robocup2022-cv-what-is-that-yolov5/"
    exec_cmd: "python3 what_is_that_yolov5.py"
  wit-yolor:
    conda_env: "what-is-that-yolor"
    exec_dir: "/home/eic/cv/robocup2022-cv-what-is-that/"
    exec_cmd: "python3 what_is_that.py"

states:
  default:
    - person-track
    - obj-yolov4
    - obj-yolov5
    - face-recog
    - wit-yolov5
    - wit-yolor
  test_problem1:
    - person-track
    - obj-yolov4
    - obj-yolov5