port: 15000
conda-exec: "conda"

processes:
  process1:
    conda_env: "testenv"
    exec_cmd: "python test.py"
  process2:
    conda_env: "testenv"
    exec_cmd: "python test.py"
  process3:
    conda_env: "testenv"
    exec_cmd: "python test.py"

states:
  default:
    - process1
    - process2
    - process3
  problem1:
    - process3
  problem2:
    - process1
    - process2