port: 15000
conda-exec: "conda"

processes:
  person-track:
    conda_env: "new-person-tracker"
    exec_dir: "/home/eic/cv/robocup2022-cv-person-tracker/"
    exec_cmd: "python3 person_tracker.py"
  obj-yolov4:
    conda_env: "yolov4"
    exec_dir: "/home/eic/cv/robocup2022-cv-YOLOv4/"
    exec_cmd: "python3 object_detection.py"
  obj-yolov5:
    conda_env: "yolov5"
    exec_dir: "/home/eic/cv/robocup2022-cv-yolov5/"
    exec_cmd: "python3 yolov5.py"
  face-recog:
    conda_env: "face-reg"
    exec_dir: "/home/eic/cv/face-recognition/"
    exec_cmd: "python3 facerecog.py"
  wit-yolov5:
    conda_env: "what-is-that-yolov5"
    exec_dir: "/home/eic/cv/robocup2022-cv-what-is-that-yolov5/"
    exec_cmd: "python3 what_is_that_yolov5.py"
  wit-yolor:
    conda_env: "what-is-that-yolor"
    exec_dir: "/home/eic/cv/robocup2022-cv-what-is-that/"
    exec_cmd: "python3 what_is_that.py"
  obj-tracker: 
    conda_env: "object-tracker"
    exec_dir: "/home/eic/cv/robocup2022-cv-object-tracker"
    exec_cmd: "python3 object_tracker.py"
  asr:
    conda_env: "nlp"
    exec_dir: "/home/eic/nlp/azure"
    exec_cmd: "python3 asr_final.py"
  rasa1:
    conda_env: "nlp"
    exec_dir: "/home/eic/nlp/rasa-nlu-v1"
    exec_cmd: "rasa run --enable"
  rasa2:
    conda_env: "nlp"
    exec_dir: "/home/eic/nlp/rasa-nlu-v1"
    exec_cmd: "rasa run actions"
  tts:
    conda_env: "nlp"
    exec_dir: "/home/eic/nlp/TTS-REST"
    exec_cmd: "python3 tts_azure.py"

states:
  default:
    - person-track
    - face-recog
    - obj-tracker
    - wit-yolov5
    - asr
    - rasa1
    - rasa2
    - tts
  test_problem1:
    - person-track
    - obj-yolov4
    - obj-yolov5